on: push
name: npm lint, test
jobs:
  lint-and-test:
    name: lint and test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: npm lint
        uses: actions/npm@master
        with:
          args: run lint:fix
      - name: npm test
        uses: actions/npm@master
        with:
          args: test